packages:
  # Aplicación principal
  - '.'

  # Módulos GDPR especializados
  - 'gdpr/*'

  # Integraciones principales
  - 'src/integrations/*'
  - 'src/zaps/*'

  # Testing y QA
  - 'tests/*'

  # Scripts y utilidades
  - 'scripts/*'
